spring:
  application:
    name: zuul-api-gateway
server:
  port: 8020
zuul:
  #Service will be mapped under the /api URI
  prefix: /api
  routes:
    service-a: 
        path: /service-a/**
        url: http://localhost:8030/
        service-id: service-a
    service-b: 
        path: /service-b/**
        url: http://localhost:8040/
        service-id: service-b


eureka: 
    client: 
        serviceUrl: 
            defaultZone: http://localhost:8761/eureka